config/routes.rb
# == Route Map (Updated 2013-12-17 09:38)
#
#              Prefix Verb   URI Pattern                         Controller#Action
#                root GET    /                                   sessions#new
#              admins GET    /admins(.:format)                   admins#index
#               users GET    /users(.:format)                    users#index
#                     POST   /users(.:format)                    users#create
#            new_user GET    /users/new(.:format)                users#new
#                user DELETE /users/:id(.:format)                users#destroy
#           members GET    /members(.:format)                members#index
#       edit_member GET    /members/:id/edit(.:format)       members#edit
#            member GET    /members/:id(.:format)            members#show
#                     PATCH  /members/:id(.:format)            members#update
#                     PUT    /members/:id(.:format)            members#update
#          employers GET    /employers(.:format)               employers#index
#                     POST   /employers(.:format)               employers#create
#       new_employer GET    /employers/new(.:format)           employers#new
#      edit_employer GET    /employers/:id/edit(.:format)      employers#edit
#           employer GET    /employers/:id(.:format)           employers#show
#                     PATCH  /employers/:id(.:format)           employers#update
#                     PUT    /employers/:id(.:format)           employers#update
#                     DELETE /employers/:id(.:format)           employers#destroy
#            openings GET    /openings(.:format)                 openings#index
#                     POST   /openings(.:format)                 openings#create
#         new_opening GET    /openings/new(.:format)             openings#new
#        edit_opening GET    /openings/:id/edit(.:format)        openings#edit
#             opening GET    /openings/:id(.:format)             openings#show
#                     PATCH  /openings/:id(.:format)             openings#update
#                     PUT    /openings/:id(.:format)             openings#update
#                     DELETE /openings/:id(.:format)             openings#destroy
#           interests GET    /interests(.:format)                interests#index
#                     POST   /interests(.:format)                interests#create
#        new_interest GET    /interests/new(.:format)            interests#new
#       edit_interest GET    /interests/:id/edit(.:format)       interests#edit
#            interest GET    /interests/:id(.:format)            interests#show
#                     PATCH  /interests/:id(.:format)            interests#update
#                     PUT    /interests/:id(.:format)            interests#update
#                     DELETE /interests/:id(.:format)            interests#destroy
#            sessions POST   /sessions(.:format)                 sessions#create
#         new_session GET    /sessions/new(.:format)             sessions#new
#             session DELETE /sessions/:id(.:format)             sessions#destroy
#     password_resets POST   /password_resets(.:format)          password_resets#create
#  new_password_reset GET    /password_resets/new(.:format)      password_resets#new
# edit_password_reset GET    /password_resets/:id/edit(.:format) password_resets#edit
#      password_reset PATCH  /password_resets/:id(.:format)      password_resets#update
#                     PUT    /password_resets/:id(.:format)      password_resets#update
#                     GET    /display/:id(.:format)              employers#display
#               purge GET    /purge(.:format)                    users#purge
#               close GET    /close(.:format)                    openings#close
#               saved GET    /saved(.:format)                    openings#saved
#                     GET    /add_saved/:id(.:format)            openings#add
#                     GET    /remove_saved/:id(.:format)         openings#remove
#               faved GET    /faved(.:format)                    employers#faved
#                     GET    /add_fave/:id(.:format)             employers#add
#                     GET    /remove_fave/:id(.:format)          employers#remove
#               login GET    /login(.:format)                    sessions#new
#            register GET    /register(.:format)                 users#new
#              logout GET    /logout(.:format)                   sessions#destroy
#          contact_us GET    /contact_us(.:format)               docs#contact_us
#      user_agreement GET    /user_agreement(.:format)           docs#user_agreement
#      privacy_policy GET    /privacy_policy(.:format)           docs#privacy_policy
#                     GET    /*path(.:format)                    sessions#destroy
#

JobBoardDemo::Application.routes.draw do
  root :to => 'sessions#new'

  resources :admins, :only => [:index]
  resources :users, only: [:index, :new, :create, :destroy]
  resources :members, only: [:index, :show, :edit, :update]
  resources :employers
  resources :openings
  resources :interests
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets, :only => [:new, :create, :edit, :update]

  match '/display/:id', to: 'employers#display', via: 'get'
  match '/saved', to: 'openings#saved', via: 'get'
  match '/add_saved/:id', to: 'openings#add', via: 'get'
  match '/remove_saved/:id', to: 'openings#remove', via: 'get'
  match '/faved', to: 'employers#faved', via: 'get'
  match '/add_fave/:id', to: 'employers#add', via: 'get'
  match '/remove_fave/:id', to: 'employers#remove', via: 'get'
  match '/purge', to: 'users#purge', via: 'get'
  match '/close', to: 'openings#close', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'get'

  match '/contact_us', to: 'docs#contact_us', via: 'get'
  match '/user_agreement', to: 'docs#user_agreement', via: 'get'
  match '/privacy_policy', to: 'docs#privacy_policy', via: 'get'

  #avoid no route matches exception - careful! if an asset isnt found this is loggin you off!
  match "*path", to: 'sessions#destroy', via: 'get'
end

app/views/shared/_create_io_button.html.erb
<% if current_role(role) %>
  <% if referrer('action') == 'new' %>
    <%= link_to 'Create another', (params[:controller] == 'openings' ? new_opening_path : new_interest_path), :class => 'btn btn-primary' %>
  <% end %>
<% end %>
<% if params[:controller] == 'interests' %>
	<%= link_to 'Return to listing', interests_path, :class => 'btn btn-info' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_int_cat_chosen.html.erb
<% if obj.interests.size == 0 %>
	<div>No <%= (obj.class.name == 'Opening' ? 'category assigned' : 'interest chosen') %> </div>
	<br>
<% else %>
	<ul>
	<% for interest in obj.interests %>
		<li><%= interest.name %></li>
	<% end %>
	</ul>
<% end %>

app/views/shared/_search_filter.html.erb
<fieldset class="nested-fieldset">
  <legend class="nested-legend"><i class="icon-filter icon-offset-half"></i> Filters</legend>
	<div class="btn-group">
	  <%= submit_tag "Apply filter(s)", :name=>nil, :class=>"btn btn-inverse", :id=>'grad-filter' %>
	  <%= link_to "Clear", {:params=>nil, :name=>nil}, :class=>"btn link2btn" %>
	</div>

	<div>
		<span id="category" style="cursor: pointer; color: #0088cc;">Job <%= (params[:controller] == 'members' ? 'Interest' : 'Category' ) %></span> <i id="job-cat-icon" class="icon-chevron-down icon-offset-half"></i>
		<% (!selected_interests.empty? ? disp = 'visible' : disp = 'none') %>
		<div id="categories" style="display:<%= disp %>;margin: 0.25em 0 0.25em 1em;">
		  <% interests.each do |interest| %>
		    <%= check_box_tag "interests[]", interest.id, selected_interests.include?(interest.id.to_s), :id=>dom_id(interest) %>
		    <%= label_tag dom_id(interest), interest.name,  :class=>"small-text list-label" %><br>
		  <% end %>
		</div>
	</div>
	<% if params[:controller] != 'members' %>
		<div>
			<span id="type" style="cursor: pointer; color: #0088cc;">Job Type</span> <i id="job-type-icon" class="icon-chevron-down icon-offset-half"></i>
			<!-- TODO: add migration, no model -->
			<div id="types" style="display: none;margin: 0.25em 0 0 1em;">
				<input type="radio" /> <span class="small-text list-label">Part-time</span><br>
				<input type="radio" /> <span class="small-text list-label">Full-time</span><br>
				<input type="radio" /> <span class="small-text list-label">Permanent</span><br>
				<input type="radio" /> <span class="small-text list-label">Temporary</span><br>
				<input type="radio" /> <span class="small-text list-label">Contract</span><br>
				<input type="radio" /> <span class="small-text list-label">Paid Intership</span><br>
			</div>
		</div>
		<div>
			<span id="location" style="cursor: pointer; color: #0088cc;">Job Location</span> <i id="job-loc-icon" class="icon-chevron-down icon-offset-half"></i>
			<div id="locations" style="display: none;margin: 0.25em 0 0 1em;">
				Within
				<%= text_field_tag 'Miles', nil, :class=>"small-text list-label", :style=>"width:30px;" %>
				miles of<br>
				<%= text_field_tag 'City', nil, :placeholder=>'City', :class=>"small-text list-label" %>
				<%= select_tag 'State', options_for_select(us_states), :name=>"state", :id=>"state", :prompt=>"State" %>
			</div>
		</div>
	<% end %>
	<div class="btn-group">
	  <%= submit_tag "Apply filter(s)", :name=>nil, :class=>"btn btn-inverse", :id=>'grad-filter' %>
	  <%= link_to "Clear", {:params=>nil, :name=>nil}, :class=>"btn link2btn" %>
	</div>
</fieldset>

app/views/shared/_set_fs_button_group.html.erb
<!-- Solves duplicate code for button group on saved and faved items -->
<%= referrer('action') %>
<% if referrer('action') == 'saved' || referrer('action') == 'faved' %>
  <%= link_to "Return to #{referrer('action')} list", "/#{referrer('action')}", :class=>'btn btn-info' %>
<% end %>

<% if params[:controller] == 'openings' %>
  <% type = "opening" %>
  <% pre = "S" %>
<% elsif params[:controller] == 'employers' %>
  <% type = "employer" %>
  <% pre = "F" %>
<% end %>

<% if !sel.include?(obj.id) %>
  <%= link_to "#{pre}ave this #{type}!", {:controller=>"#{params[:controller]}", :action=>'add', :id=>obj.id}, :class=>'btn btn-success' %>
<% else %>
  <%= link_to 'Make note', '#', data: {confirm: 'Not yet implemented'}, :class=>'btn btn-primary' %>
  <%= link_to "Remove from #{pre.downcase}aved list", {:controller=>"#{params[:controller]}", :action=>'remove', :id=>obj.id }, :class=>'btn btn-danger', data: {confirm: "This will delete any saved notes.\n\nAre you sure?"} %>
<% end %>