config/routes.rb
# == Route Map (Updated 2013-12-17 09:38)
#
#              Prefix Verb   URI Pattern                         Controller#Action
#                root GET    /                                   sessions#new
#              admins GET    /admins(.:format)                   admins#index
#               users GET    /users(.:format)                    users#index
#                     POST   /users(.:format)                    users#create
#            new_user GET    /users/new(.:format)                users#new
#                user DELETE /users/:id(.:format)                users#destroy
#           members GET    /members(.:format)                members#index
#       edit_member GET    /members/:id/edit(.:format)       members#edit
#            member GET    /members/:id(.:format)            members#show
#                     PATCH  /members/:id(.:format)            members#update
#                     PUT    /members/:id(.:format)            members#update
#          employers GET    /employers(.:format)               employers#index
#                     POST   /employers(.:format)               employers#create
#       new_employer GET    /employers/new(.:format)           employers#new
#      edit_employer GET    /employers/:id/edit(.:format)      employers#edit
#           employer GET    /employers/:id(.:format)           employers#show
#                     PATCH  /employers/:id(.:format)           employers#update
#                     PUT    /employers/:id(.:format)           employers#update
#                     DELETE /employers/:id(.:format)           employers#destroy
#            openings GET    /openings(.:format)                 openings#index
#                     POST   /openings(.:format)                 openings#create
#         new_opening GET    /openings/new(.:format)             openings#new
#        edit_opening GET    /openings/:id/edit(.:format)        openings#edit
#             opening GET    /openings/:id(.:format)             openings#show
#                     PATCH  /openings/:id(.:format)             openings#update
#                     PUT    /openings/:id(.:format)             openings#update
#                     DELETE /openings/:id(.:format)             openings#destroy
#           interests GET    /interests(.:format)                interests#index
#                     POST   /interests(.:format)                interests#create
#        new_interest GET    /interests/new(.:format)            interests#new
#       edit_interest GET    /interests/:id/edit(.:format)       interests#edit
#            interest GET    /interests/:id(.:format)            interests#show
#                     PATCH  /interests/:id(.:format)            interests#update
#                     PUT    /interests/:id(.:format)            interests#update
#                     DELETE /interests/:id(.:format)            interests#destroy
#            sessions POST   /sessions(.:format)                 sessions#create
#         new_session GET    /sessions/new(.:format)             sessions#new
#             session DELETE /sessions/:id(.:format)             sessions#destroy
#     password_resets POST   /password_resets(.:format)          password_resets#create
#  new_password_reset GET    /password_resets/new(.:format)      password_resets#new
# edit_password_reset GET    /password_resets/:id/edit(.:format) password_resets#edit
#      password_reset PATCH  /password_resets/:id(.:format)      password_resets#update
#                     PUT    /password_resets/:id(.:format)      password_resets#update
#                     GET    /display/:id(.:format)              employers#display
#               purge GET    /purge(.:format)                    users#purge
#               close GET    /close(.:format)                    openings#close
#               saved GET    /saved(.:format)                    openings#saved
#                     GET    /add_saved/:id(.:format)            openings#add
#                     GET    /remove_saved/:id(.:format)         openings#remove
#               faved GET    /faved(.:format)                    employers#faved
#                     GET    /add_fave/:id(.:format)             employers#add
#                     GET    /remove_fave/:id(.:format)          employers#remove
#               login GET    /login(.:format)                    sessions#new
#            register GET    /register(.:format)                 users#new
#              logout GET    /logout(.:format)                   sessions#destroy
#          contact_us GET    /contact_us(.:format)               docs#contact_us
#      user_agreement GET    /user_agreement(.:format)           docs#user_agreement
#      privacy_policy GET    /privacy_policy(.:format)           docs#privacy_policy
#                     GET    /*path(.:format)                    sessions#destroy
#

JobBoardDemo::Application.routes.draw do
  root :to => 'sessions#new'

  resources :admins, :only => [:index]
  resources :users, only: [:index, :new, :create, :destroy]
  resources :members, only: [:index, :show, :edit, :update]
  resources :employers
  resources :openings
  resources :interests
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets, :only => [:new, :create, :edit, :update]

  match '/display/:id', to: 'employers#display', via: 'get'
  match '/saved', to: 'openings#saved', via: 'get'
  match '/add_saved/:id', to: 'openings#add', via: 'get'
  match '/remove_saved/:id', to: 'openings#remove', via: 'get'
  match '/faved', to: 'employers#faved', via: 'get'
  match '/add_fave/:id', to: 'employers#add', via: 'get'
  match '/remove_fave/:id', to: 'employers#remove', via: 'get'
  match '/purge', to: 'users#purge', via: 'get'
  match '/close', to: 'openings#close', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'get'

  match '/contact_us', to: 'docs#contact_us', via: 'get'
  match '/user_agreement', to: 'docs#user_agreement', via: 'get'
  match '/privacy_policy', to: 'docs#privacy_policy', via: 'get'

  #avoid no route matches exception - careful! if an asset isnt found this is loggin you off!
  match "*path", to: 'sessions#destroy', via: 'get'
end

app/models/employer.rb
# == Schema Information
#
# Table name: employers
#
#  id             :integer          not null, primary key
#  company        :string(50)
#  description    :text
#  created_at     :datetime
#  updated_at     :datetime
#  skip           :boolean          default(FALSE)
#  openings_count :integer          default(0)
#  city           :string(30)
#  state          :string(30)
#  zip_code       :string(10)
#

class Employer < ActiveRecord::Base
  has_one :user, :as => :role, dependent: :destroy
  has_many :openings, dependent: :destroy
  #members-employers join (favoriteds)
  has_many :favoriteds
  has_many :members, :through => :favoriteds

  delegate :email, :created_at, :updated_at, :to => :user, :prefix => true

  #Only validate if not creating user
  validates :company,
    :presence => true,
    :length => { :maximum => 50 },
    :on => :update
  validates :city,
    :presence => true,
    :length => { :maximum => 30 },
    :on => :update
  validates :state,
    :presence => true,
    :length => { :maximum => 30 },
    :on => :update
  validates :zip_code,
    :presence => true,
    :length => { :maximum => 10 },
    :on => :update
  validates :description,
    :presence => true,
    :length => {
      :maximum => 5000,
      :message => '
is too long (maximum is 5000 characters - includes HTML formatting characters)
'
    },
    :on => :update
end

app/controllers/employers_controller.rb
#Employer user REST actions
class EmployersController < ApplicationController
  include Roles

  before_action :set_employer, only: [:edit, :update, :destroy]

  before_action :is_admin, only: [:index, :new, :create, :destroy]
  before_action :is_admin_or_np, only: [:show, :edit, :update]
  before_action :is_member, only: [:display, :add, :remove, :faved]

  ###GET /employers
  def index
    @employers = Employer.includes(:user)
  end

  ##GET /employers/1
  def show
    @employer = Employer.includes(:user).find(params[:id])
    @openings = @employer.openings
  end

  ###GET /employers/new
  def new
    @user = User.new
  end

  ###POST /employers
  def create
    @user = User.new(user_params)
    @user.generate_token(:password_reset_token)
    #Only employers will be registered from the new form
    @user.role = Employer.new()
    if @user.save
      #TODO: remove if when email ready on production
      @user.send_invitation_welcome if Rails.env.development?
      redirect_to employers_path,
        notice: 'Employer successfully created and email invitation sent.'
    else
      render 'new'
    end
  end

  #profile
  ###GET /employers/1/edit
  def edit
    @user = @employer.user
    @selected_number = @user.def_table_disp
  end

  #profile handler
  ###PATCH/PUT /members/1
  def update
    @user = @employer.user
    if @employer.update(employer_params) && @user.update_attribute('def_table_disp', params[:def_table_disp])
      redirect_to edit_employer_path(@employer),
        notice: 'Profile successfully updated.'
    else
      @selected_number = params[:def_table_disp] ||= 10
      render 'edit'
    end
  end

  ###DELETE /employer/1
  def destroy
    @employer.destroy
    redirect_to employers_path, notice: 'Employer deleted successfully.'
  end

  ###Non-RESTful actions
  #Member adds Employer to faved list
  def add
    cur_user = current_user.role_id
    pid = params[:id]
    if Member.find(cur_user).favoriteds.create(
      :member_id=>cur_user, :employer_id=>pid
    )
      flash[:notice] = 'Employer added to Faved list!'
    else
      flash[:alert] = 'There was a problem adding Employer to Faved list.'
    end
    redirect_to :action => 'display', :id =>(pid)
  end

  #Member removes Employer from faved list
  def remove
    pid = params[:id]
    @id = Favorited.find_by_sql([
      "SELECT id
      FROM favoriteds
      WHERE member_id = ?
      AND employer_id = ?",
      current_user.role_id, pid
    ])
    if Favorited.delete(@id)
      flash[:notice] = 'Employer removed from Faved list!'
    else
      flash[:alert] = 'There was a problem removing Employer from Faved list.'
    end
    redirect_to :action => 'display', :id =>(pid)
  end

  #For Members to view profile info
  def display
    @employer = Employer.find(params[:id])
    qry = Opening.find_by_sql([
      "SELECT employers.id FROM employers
      LEFT OUTER JOIN favoriteds ON favoriteds.employer_id = employers.id
      WHERE favoriteds.member_id = ?",
      current_user.role_id
    ])
    @selected_favoriteds = qry.collect(&:id)
  end

  #Get Faved list
  def faved
    #Not sure why the below doesnt work?
    #@faved = Employer.includes(:favoriteds, :user)
    #.where('favoriteds.member_id = ?', current_user.role_id)
    #.references(:favoriteds, :user)
    @faved = Employer.find_by_sql([
      "SELECT employers.*, users.email FROM employers
      LEFT OUTER JOIN favoriteds ON favoriteds.employer_id = employers.id
      INNER JOIN users ON users.role_id = employers.id
      WHERE favoriteds.member_id = ?
      GROUP BY employers.id",
      current_user.role_id
    ])
  end

  private
    ###Use callbacks to share common setup or constraints between actions.
    #Retreives the opening by requested parameter
    #IF it is owned by the current NP AND it exists
    def set_employer
      pid = params[:id]
      if Employer.exists?(pid)
        @employer = Employer.find(pid)
        if (
          !current_role(Admin) &&
          (@employer.id != current_user.role_id) ||
          !@employer
        )
          print "\n\nset_employer not current user\n\n"
          redirect_to logout_path
        end
      else
        redirect_to logout_path
      end
    end
    ###Never trust parameters from the scary internet,
    #only allow the white list through.
    def employer_params
      params.require(:employer).permit(
        :company,
        :description,
        :city,
        :state,
        :zip_code,
        :skip
      )
    end
    def user_params
      params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :force_reset
      )
    end
  #end private
end

app/views/employers/display.html.erb
<fieldset>
	<legend><%= @employer.company %> - <%= @employer.city %>, <%= @employer.state %></legend>
	<label>Email:</label>
	<div class="field"><%= mail_to @employer.user_email, @employer.user_email %></div>
	<label>Description:</label>
	<div class="field"><%= sanitized(@employer.description) %><div>
	<br>
	<div class="btn-group">
		<% if referrer('action') == 'show' %>
			<%= link_to 'Return to opening', 'javascript:history.back()', :class => "btn btn-inverse" %>
		<% end %>
		<% (session[:last_search] ? back = session[:last_search] : back = openings_path) %>
		<%= link_to 'Return to listing', back, :class => 'btn' %>
		<% if current_role(Member) %>
			<%= render '/shared/set_fs_button_group', :obj => @employer, :sel => @selected_favoriteds %>
		<% end %>
	</div>
</fieldset>

app/views/employers/edit.html.erb
<fieldset>
	<legend>Update Profile</legend>
	<%= display_note('agree') %>
	<%= tinymce %>
	<%= form_for(@employer) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <%= prewrap_form('employer', 'Company','star') %>
	  <%= f.text_field :company, :class => "textfield", :autofocus=>"autofocus" %>
	  <%= postwrap_form('Company is required') %>

	  <%= prewrap_form('employer', 'City','map-marker', 'left') %>
	  <%= f.text_field :city, :class => "textfield", :id => "np-city" %>
	  <%= postwrap_form('City is required') %>

	  <%= prewrap_form('employer', 'State','map-marker', 'left') %>
	  <%= f.text_field :state, :class => "textfield", :id => "np-state" %>
	  <%= postwrap_form('State is required') %>

	  <%= prewrap_form('employer', 'Zip Code','map-marker', 'left') %>
	  <%= f.text_field :zip_code, :class => "textfield", :id => "np-zip" %>
	  <%= postwrap_form('Zip Code is required') %>

	  <br class="clear">

	  <label>
	    <%= f.label :description %>&nbsp;<span class="add-on"><a href="#" title="Description is required" tabindex="-1"><i class="icon-asterisk"></i></a></span>
	  </label>
	  <div class="field">
	    <%= f.text_area :description, :class => "textarea tinymce", :id => "np-desc" %>
	  </div>
	  <%= display_note('emp_desc') %>
		<fieldset id="np-settings" class="nested-fieldset"><legend class="nested-legend">Default Preferences</legend>
	    <div class="field">
	    	<%= label_tag :def_table_disp, "Number of rows to show in table listings", :class=>'list-label' %><br>
				<%= select_tag :def_table_disp, options_for_select(TABLE_ROWS, @selected_number), :style=>'width:75px;' %>
	    </div>
	  </fieldset>
	  <hr>
	  <label>
	    <%= f.check_box :skip, :class => "checkbox", :id => 'skip' %>
	    <%= label_tag :skip, "Skip this next time" %>&nbsp;<span class="add-on"><a href="#" title="Go directly to Manage Openings after logging in." tabindex="-1"><i class="icon-question-sign"></i></a></span>
	  </label>
	  <% case referrer('action')
	      when "edit"
	        if f.object && f.object.errors.any?
	          return_text = "Cancel"
	        else
	          return_text = "Return to listing"
	        end
	      else
	        return_text = "Cancel"
	  end %>
	  <br><br>
	  <div class="btn-group">
	    <%= f.submit "Save changes", :class => "btn", :id => 'np-submit' %>
	    <% if current_role(Admin) %>
	      <%= link_to "#{return_text}", employers_path, :class => "btn btn-inverse link2btn", id: 'np-cancel' %>
	    <% end %>
	  </div>
	<% end %>
</fieldset>

app/views/employers/faved.html.erb
<fieldset>
  <legend>Favorite Employers</legend>
  <!-- <div class="row-fluid">
    <div class="span12">
      <fieldset class="nested-fieldset">
        <legend class="nested-legend">Instructions</legend> -->
<%= hidden_field_tag "dLength", "#{@show_entries}" %>
<table class="datatables" id="dt-faved">
  <thead>
    <tr>
      <th>Company</th>
      <th>Email</th>
      <th>Openings</th>
    </tr>
  </thead>
  <tbody>
    <% @faved.each do |employer| %>
      <tr>
        <td>
          <%= link_to "#{employer.company}",
              {:controller => 'employers',
              :action => 'display',
              :id => "#{employer.id}"} %>
        </td>
        <td><%= mail_to employer.email %></td>
        <td>
          <span class="badge
            <%= (employer.openings_count > 0 ? 'badge-info' : 'badge') %>
          ">
            <%= employer.openings_count %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th class="foot-filter">Company filter</th>
      <th class="foot-filter">Email filter</th>
    </tr>
  </tfoot>
</table>
      </fieldset>
    </div>
    <!-- <div class="span2">
      <%#= form_tag openings_path, :method => 'get' do %>
        <%#= render 'shared/search_filter', :interests => @interests, :selected_interests => @selected_interests %>
      <%# end %>
    </div> -->
  <!-- </div> -->
  <div>
    <%= link_to 'Return to listing', openings_path, :class => 'btn' %>
    <a href="javascript: window.location.reload()",
    class ="btn right">Clear filter(s)</a>
  </div>
</fieldset>

<!-- optimized queries -->

app/views/employers/index.html.erb
<fieldset>
  <legend>Manage Employers <i class="icon-star icon-offset"></i></legend>
  <%= display_note('employers') %>
  <div class="btn-group">
    <%= link_to 'Create new Employer', new_employer_path, :class => 'btn btn-primary' %>
    <%= link_to 'Return to menu', admins_path, :class => 'btn btn-info' %>
  </div>
  <br>
  <%= hidden_field_tag "dLength", "#{@show_entries}" %>
  <table class="datatables" id="dt-employers">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>ID</th>
        <th>Email</th>
        <th>Company Name</th>
        <th>Openings</th>
        <th>Created</th>
        <th>Profile Updated</th>
      </tr>
    </thead>
    <tbody>
      <% @employers.each do |employer| %>
        <tr>
          <td>
            <div class="btn-group btn-group-xs">
              <%= link_to 'Show', employer_path(employer), :class => "btn btn-mini btn-success", :id => "show" %>
              <%= link_to 'Edit', edit_employer_path(employer), :class => "btn btn-mini btn-warning", :id => "edit", data: { confirm: "Be cautious when editing another user\'s input. This could cause confusion and/or mistrust of the system.\n\nAre you sure?" } %>
              <% if !employer.company? %>
                <% msg = "WARNING: Continuing will delete this Employer user.\n\nAre you sure? This action cannot be undone." %>
                <% btn_type = "" %>
              <% else %>
                <% msg = "STRONG WARNING: Continuing will delete this Employer user and ALL associated Openings.\n\nAre you sure? This action cannot be undone." %>
                <% btn_type = 'btn-danger' %>
              <% end %>
              <%= link_to 'Delete', employer, method: :delete, :class => "btn btn-mini #{btn_type}", :id => "delete", data: { confirm: msg } %>
            </div>
          </td>
          <td><%= employer.id %></td>
          <td><%= employer.user_email %></td>
          <td><%= (!employer.company? ? "<span class='red'>Incomplete profile</span>".html_safe : employer.company) %></td>
          <td><span class="badge <%= (employer.openings_count > 0 ? 'badge-info' : 'badge') %>"><%= employer.openings_count %></span></td>
          <td><%= employer.user_created_at.strftime('%m/%d/%Y') %></td>
          <td><%= (!employer.company? ? "<span class='red'>Never</span>".html_safe : employer.user_updated_at.strftime('%m/%d/%Y %I:%m %p')) %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th>&nbsp;</th>
        <th class="foot-filter">ID filter</th>
        <th class="foot-filter">Email filter</th>
        <th class="foot-filter">Company filter</th>
        <th>&nbsp;</th>
        <th class="foot-filter"></th>
        <th class="foot-filter"></th>
      </tr>
    </tfoot>
  </table>
  <div class="btn-group">
    <%= link_to 'Create new Employer', new_employer_path, :class => 'btn btn-primary' %>
    <%= link_to 'Return to menu', admins_path, :class => 'btn btn-info' %>
  </div>
  <div class="right">
    <a href="javascript: window.location.reload()", class ="btn">Clear filter(s)</a>
  </div>
</fieldset>

<!-- optimized queries -->

app/views/employers/new.html.erb
<fieldset>
  <legend>Create Employer <i class="icon-star-empty icon-offset"></i></legend>
  <p class="info">
    Instructions: Entering an email address will create a temporary password and send an invitation to the person at that address. The potential Employer user will be requested to change their temporary password when they log on for the first time.
  </p>
	<%= form_for @user, :as => :post, :url => employers_path do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <%= prewrap_form('user', 'Email','envelope') %>
	  <%= text_field_tag "#{:user}[email]", params[:email], :class => "textfield", :autofocus=>"autofocus" %>
	  <%= postwrap_form('Email is required') %>
	  <%= hidden_field(:user, :password, :value => 'Temp4Chg!') %>
	  <%= hidden_field(:user, :password_confirmation, :value => 'Temp4Chg!') %>
	  <%= hidden_field(:user, :force_reset, :value => true) %>
	  <div class="btn-group">
	    <%= submit_tag "Submit", :class => "btn" %>
	    <%= link_to 'Cancel', (URI(request.referer).path rescue :back), :class => "btn btn-inverse link2btn" %>
	  </div>
	<% end %>
</fieldset>

app/views/employers/show.html.erb
<div class="btn-group">
	<%= link_to 'Return to listing', employers_path, :class => 'btn btn-info' %>
</div>
<fieldset>
	<legend><%= @employer.company || "Incomplete profile" %></legend>
	<h4>Location:</h4>
	<div class="field"><%= @employer.city %>, <%= @employer.state %></div>
	<h4>Email:</h4>
	<div class="field"><%= mail_to @employer.user_email, @employer.user_email %></div>

	<h4>Description:</h4>
	<div class="field"><%= sanitized(@employer.description) %><div>
	<br>
	<h4 class="center" id="openings-header">OPENINGS</h4>
	<% if @openings.count > 0 %>
		<%= hidden_field_tag "dLength", "#{@show_entries}" %>
		<table class="datatables" id="dt-openings">
	    <thead>
	      <tr>
	        <th></th>
	        <th>ID</th>
	        <th>Active?</th>
	        <th>Position</th>
	        <th>Date Open</th>
	        <th>Date Closed</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @openings.each do |opening| %>
	        <tr>
	          <td>

	          	<%= set_opening_actions_button_group(opening) %>

	          </td>
	          <td><%= opening.id %></td>
	          <td><%= opening.active ? 'Yes' : "<span class='red'>No</span>".html_safe %></td>
	          <td><%= truncate(opening.position, length: 50) %> - <%= opening.city %>, <%= opening.state %></td>
	        	<td><%= display_open_date(opening) %></td>
	          <td><%= display_closed_date(opening) %></td>
	        </tr>
	      <% end %>
	    </tbody>
			<tfoot>
	      <tr>
	        <th></th>
	        <th>ID filter</th>
	        <th>Active filter</th>
	        <th>Position filter</th>
	        <th></th>
	        <th></th>
	      </tr>
	    </tfoot>
	  </table>
  <% else %>
  	<p style="margin-top:10px;">None created.</p>
  <% end %>
	<div class="btn-group">
		<%= link_to 'Return to listing', employers_path, :class => 'btn btn-info' %>
	</div>
  <div class="right">
    <a href="javascript: window.location.reload()", class ="btn">Clear filter(s)</a>
  </div>
	<%= display_note('date') if @openings.count > 0 %>
</fieldset>

<!-- optimized queries -->