config/routes.rb
# == Route Map (Updated 2013-12-17 09:38)
#
#              Prefix Verb   URI Pattern                         Controller#Action
#                root GET    /                                   sessions#new
#              admins GET    /admins(.:format)                   admins#index
#               users GET    /users(.:format)                    users#index
#                     POST   /users(.:format)                    users#create
#            new_user GET    /users/new(.:format)                users#new
#                user DELETE /users/:id(.:format)                users#destroy
#           members GET    /members(.:format)                members#index
#       edit_member GET    /members/:id/edit(.:format)       members#edit
#            member GET    /members/:id(.:format)            members#show
#                     PATCH  /members/:id(.:format)            members#update
#                     PUT    /members/:id(.:format)            members#update
#          employers GET    /employers(.:format)               employers#index
#                     POST   /employers(.:format)               employers#create
#       new_employer GET    /employers/new(.:format)           employers#new
#      edit_employer GET    /employers/:id/edit(.:format)      employers#edit
#           employer GET    /employers/:id(.:format)           employers#show
#                     PATCH  /employers/:id(.:format)           employers#update
#                     PUT    /employers/:id(.:format)           employers#update
#                     DELETE /employers/:id(.:format)           employers#destroy
#            openings GET    /openings(.:format)                 openings#index
#                     POST   /openings(.:format)                 openings#create
#         new_opening GET    /openings/new(.:format)             openings#new
#        edit_opening GET    /openings/:id/edit(.:format)        openings#edit
#             opening GET    /openings/:id(.:format)             openings#show
#                     PATCH  /openings/:id(.:format)             openings#update
#                     PUT    /openings/:id(.:format)             openings#update
#                     DELETE /openings/:id(.:format)             openings#destroy
#           interests GET    /interests(.:format)                interests#index
#                     POST   /interests(.:format)                interests#create
#        new_interest GET    /interests/new(.:format)            interests#new
#       edit_interest GET    /interests/:id/edit(.:format)       interests#edit
#            interest GET    /interests/:id(.:format)            interests#show
#                     PATCH  /interests/:id(.:format)            interests#update
#                     PUT    /interests/:id(.:format)            interests#update
#                     DELETE /interests/:id(.:format)            interests#destroy
#            sessions POST   /sessions(.:format)                 sessions#create
#         new_session GET    /sessions/new(.:format)             sessions#new
#             session DELETE /sessions/:id(.:format)             sessions#destroy
#     password_resets POST   /password_resets(.:format)          password_resets#create
#  new_password_reset GET    /password_resets/new(.:format)      password_resets#new
# edit_password_reset GET    /password_resets/:id/edit(.:format) password_resets#edit
#      password_reset PATCH  /password_resets/:id(.:format)      password_resets#update
#                     PUT    /password_resets/:id(.:format)      password_resets#update
#                     GET    /display/:id(.:format)              employers#display
#               purge GET    /purge(.:format)                    users#purge
#               close GET    /close(.:format)                    openings#close
#               saved GET    /saved(.:format)                    openings#saved
#                     GET    /add_saved/:id(.:format)            openings#add
#                     GET    /remove_saved/:id(.:format)         openings#remove
#               faved GET    /faved(.:format)                    employers#faved
#                     GET    /add_fave/:id(.:format)             employers#add
#                     GET    /remove_fave/:id(.:format)          employers#remove
#               login GET    /login(.:format)                    sessions#new
#            register GET    /register(.:format)                 users#new
#              logout GET    /logout(.:format)                   sessions#destroy
#          contact_us GET    /contact_us(.:format)               docs#contact_us
#      user_agreement GET    /user_agreement(.:format)           docs#user_agreement
#      privacy_policy GET    /privacy_policy(.:format)           docs#privacy_policy
#                     GET    /*path(.:format)                    sessions#destroy
#

JobBoardDemo::Application.routes.draw do
  root :to => 'sessions#new'

  resources :admins, :only => [:index]
  resources :users, only: [:index, :new, :create, :destroy]
  resources :members, only: [:index, :show, :edit, :update]
  resources :employers
  resources :openings
  resources :interests
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets, :only => [:new, :create, :edit, :update]

  match '/display/:id', to: 'employers#display', via: 'get'
  match '/saved', to: 'openings#saved', via: 'get'
  match '/add_saved/:id', to: 'openings#add', via: 'get'
  match '/remove_saved/:id', to: 'openings#remove', via: 'get'
  match '/faved', to: 'employers#faved', via: 'get'
  match '/add_fave/:id', to: 'employers#add', via: 'get'
  match '/remove_fave/:id', to: 'employers#remove', via: 'get'
  match '/purge', to: 'users#purge', via: 'get'
  match '/close', to: 'openings#close', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/register', to: 'users#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'get'

  match '/contact_us', to: 'docs#contact_us', via: 'get'
  match '/user_agreement', to: 'docs#user_agreement', via: 'get'
  match '/privacy_policy', to: 'docs#privacy_policy', via: 'get'

  #avoid no route matches exception - careful! if an asset isnt found this is loggin you off!
  match "*path", to: 'sessions#destroy', via: 'get'
end

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="footer-links">
		<ul>
			<li><%= link_to_unless_current	'Privacy Policy', "/privacy_policy.html", :id => 'privacy_policy', :class => 'dialog' %></li>
			<li><%= link_to_unless_current "User Agreement", "/user_agreement.html", :id => 'user_agreement', :class => 'dialog' %></li>
			<li><%= link_to "Contact Us", "contact_us.html", :id => '/contact_us', :class => 'dialog' %></li>
		</ul>
	</div>
	<br class="clear">
  &copy; 2013 <%= link_to "The Art of Tech, LLC.", 'http://theartoftechllc.com', target: "_blank", :class => "footer-link" %> <i class="icon-star icon-share" title="Offsite link"></i> All rights reserved.
</footer>

<!-- If pages are caching: ?#{CGI::escape(Time.now.to_s)} -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header>
  <div class="container" style="padding: 0; margin:0; background-color:rgb(159,167,214)">
    <div class="center" style="background: url(<%= randomized_background_image %>) no-repeat center center;min-height: 150px;">
      <div id="banner">
        <img src="/assets/job-board-demo-header.gif">
      </div>
    </div>
  </div>
  <% if current_user %>
    <div id="status">
      Welcome <%= display_current_name || display_current_email %>
      <%= "(Member)" if current_role(Member) %>
      <%= "(Employer)" if current_role(Employer) %>
      <%= "(Administrator)" if current_role(Admin) %>
    </div>
  <% end %>
  <nav class="header-links navbar navbar-default right" role="navigation">
    <ul>
      <% if current_user %>
        <% if !current_role(Admin) %>
          <!-- Profile -->
          <li><%= link_to_unless_current "Profile", [:edit, current_user.role] %></li>
          <!-- Search Members (NP) -->
          <% if current_role(Employer) && !current_user.role.company.blank? %>
            <li><%= link_to_unless_current "Search Job Seekers", members_path %></li>
          <% end %>
          <!-- Search/Manage Openings -->
          <% if current_role(Member) && !current_user.role.first_name.blank? %>
            <li><%= link_to_unless_current "Search Openings", openings_path %></li>
          <% elsif current_role(Employer) && !current_user.role.company.blank? %>
            <li><%= link_to_unless_current "Manage Openings", openings_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to_unless_current "Menu", admins_path %></li>
        <% end %>
        <!-- Log out -->
        <li><%= link_to_unless_current "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to_unless_current "Register", register_path %></li>
        <li><%= link_to_unless_current "Log In",  login_path %></li>
      <% end %>
    </ul>
  </nav>
  <br class="clear">
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : APPNAME %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Job Board Demo" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar"> <!-- navbar-fixed-top -->
      <div class="row-fluid header-adjust">
        <div class="span12">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
          <div class="row-fluid header-adjust">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    <% if Rails.env.development? %>
      <div id="alert">
        <h3 class="center">DEBUGGER</h3>
        <ul>
          <li>User: <%= (display_current_email.nil? ? display_current_name : display_current_email) rescue "None" %></li>
          <li>User ID: <%= current_user.nil? ? 0 : current_user.id %></li>
          <li>Role: <%= (display_current_role.empty? ? 'None' : display_current_role) %></li>
          <li>Role ID: <%= current_user.nil? ? 0 : current_user.role_id %></li>
        </ul>
        <%= debug(params)  %>
      </div>
    <% end %>
  </body>
</html>